export const data = {
    name: "Jesus Alejandro Guillen Luna",
    ubication: "Tuxtla Gutierrez, Chiapas",
    phone: "965-105-2289",
    facebook: "Alejandro GL",
    instagram: "itsalex.luna",
    profession: "Engineering Student in Software Development",
    icoUser: "/icons/perfil.png",
    icoUbication: "/icons/ubicacion.png",
    icoPhone: "/icons/telefono.png",
    icoFacebook: "/icons/facebook.png",
    icoInstagram: "/icons/instagram.png",
    icoMundo: "/icons/mundo.png",
    icoFormacion: "/icons/formacion.png",
    icoHabilidades: "/icons/habilidades.png",
    icoLaboral: "/icons/cerebro.png",
    icoIdiomas: "/icons/idiomas.png",
    aboutUs: "Me llamo Jesus Alejandro tengo 20 años y actualmente estoy estudiando la carrera de Desarrollo de Software en la Universidad Politecnica de Chiapas.  Me gusta mucho el diseño de paginas web e interactuar en el diseño y sus colores.",
    telesecundaria: "Esc. Telesecunadaria Emilio Rabasa Estebanell",
    preparatoria: "Esc. Preparatoria Revolucion",
    universidad: "Universidad Politecnica de Chiapas",
    javascript: "JavaScript",
    java: "Java",
    C: "C++",
    c: "C",
    experencia: "He trabajado en varios proyectos integradores de la universidad, en la creacion de paginas web asi como aplicaciones web, con forme a estas experencias he aprendido mucho en el ambito de HTML, JS Y CSS y a su vez diseño de interfases lo cual me gustaria aprender mas.",
    español: "Español",
    ingles: "Ingles",


}